[package]
name = "picocraft_core"
# description = ""
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
log.workspace = true
heapless = { workspace = true, features = ["embedded-io-v0.7"] }
thiserror.workspace = true

uuid = { workspace = true, features = ["v3", "v4"] }

core-json-derive.workspace = true
core-json-traits.workspace = true

embedded-io.workspace = true
embedded-io-async.workspace = true
<<<<<<< ours
bitflags = "2.11.0"

[lib]
doctest = false
||||||| ancestor
=======

[lib]
doctest = false
>>>>>>> theirs
